container: docker.io/rpavlyuk/c7-broadlink
created: 2017-10-12 16:53:53.501852
name: broadlink
ports:
        8888/tcp: 8888
volumes: {}
privileged: false
tty: false
working_dir: /root
environment: {}
network_mode: host
