container: docker.io/rpavlyuk/c7-broadlink
created: 2017-10-12 16:53:53.501852
name: broadlink
ports:
        8888/tcp: 8888
volumes:
        /sys/fs/cgroup:
                bind: /sys/fs/cgroup
                mode: ro
privileged: false
tty: false
working_dir: /root
environment: {}
network_mode: host
command:
        host:
                post: docker exec broadlink perl -pi -e "s/\=127.0.0.1/\=192.168.1.5/gi" /etc/zabbix/zabbix_agentd.conf && docker exec broadlink systemctl restart zabbix-agent
