#!/usr/bin/env python3

import broadlink
import sys
import argparse
import time
import socket

def auto_int(x):
    return int(x, 0)

### Main routine
def main(args):

    # defaults
    retries_count = 3 # try N times before risinng an error
    d_auth = False

    # args
    host = args.host
    mac = bytearray.fromhex(args.mac)

    dev = broadlink.gendevice(args.type, (host, 80), mac)
    dev.timeout = 5

    # LEt's try to initiate the Device
    i = 0
    is_timeout = 0
    while (i<retries_count):
      i+=1
      try:
        d_auth = dev.auth()
        is_timeout = 0
        break
      except socket.timeout as err:
        # do nothing, one more loop
        is_timeout = 1
        continue
      except:
        print("Device authorization failed", file=sys.stderr)
        print(sys.exc_info(), file=sys.stderr)

    # Okay, probably there was a timeout after 3 tries ...
    if is_timeout:
      raise Exception("Got socket timeout after {} retries to authorize on the device".format(retries_count))

    # Now, let's check of the authorization was ever made
    if not d_auth:
      raise Exception("Device authorization hasn't been made. Probably, it is not configured or is not supported by Python Broadlink library")    


    if args.key == 'power':

       # let's loop to avoid timeouts
      i = 0
      is_timeout = 0
      while (i<retries_count):
        i+=1
        try:
          if dev.check_power():
            print(1)
          else:
            print(0)
          is_timeout = 0
          break
        except socket.timeout as err:
          # do nothing, one more loop
          is_timeout = 1
          continue
        except:
          print("Failed to obtain power state from sensor", file=sys.stderr)
          print(sys.exc_info(), file=sys.stderr)

    elif args.key == 'energy':
      # let's loop again
      i = 0
      is_timeout = 0
      while (i<retries_count):
        i+=1
        try:
          energy = dev.get_energy()
          print(energy)
          is_timeout = 0
          break
        except socket.timeout as err:
          # do nothing, one more loop
          is_timeout = 1
          continue
        except:
          print("Failed to obtain energy value from sensor", file=sys.stderr)
          print(sys.exc_info(), file=sys.stderr)

      # Okay, probably there was a timeout after 3 tries ...
      if is_timeout:
        raise Exception("Got socket timeout after {} retries to obtain energy value".format(retries_count))




# Standard boilerplate to call the main() function to begin
# the program.
if __name__ == '__main__':
    
    parser = argparse.ArgumentParser(fromfile_prefix_chars='@');
    parser.add_argument("--mac", help="mac address (hex reverse), as used by python-broadlink library", required=True)
    parser.add_argument("--type", type=auto_int, default=0x2711, help="type of device")
    parser.add_argument("--host", help="device IP address", required=True)
    parser.add_argument("--key", help="data key", choices=['power', 'energy'], default='power')
    args = parser.parse_args()

    main(args)
